# Generated by Django 5.1.1 on 2025-06-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dopamine', '0005_product_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
