# Generated by Django 5.1.1 on 2025-06-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dopamine', '0006_recipe_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('vegetarian', 'Món chay'), ('meat', 'Món mặn'), ('dessert', 'Món tráng miệng')], default='meat', max_length=50),
        ),
    ]
