# Generated by Django 5.1.1 on 2025-07-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dopamine', '0008_recipestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
