# Generated by Django 5.1.1 on 2025-07-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dopamine', '0009_recipe_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='icon',
        ),
    ]
