# Generated by Django 5.1.1 on 2025-07-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dopamine', '0010_remove_recipe_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='step_marker',
            field=models.CharField(blank=True, help_text='Ví dụ: A, B, C hoặc ký hiệu đặc biệt (👉🏼, ★, ...)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='steps/'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='step_number',
            field=models.PositiveIntegerField(),
        ),
    ]
