# Generated by Django 5.1.1 on 2025-07-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dopamine', '0011_recipestep_step_marker_alter_recipestep_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestep',
            name='step_marker',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='step_number',
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_step', to='dopamine.recipe'),
        ),
    ]
