# Generated by Django 5.1.1 on 2025-07-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dopamine', '0012_remove_recipestep_step_marker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Món chay'), ('meat', 'Món mặn'), ('dessert', 'Món tráng miệng')], max_length=50, null=True),
        ),
    ]
