# Generated by Django 5.1.1 on 2025-07-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dopamine', '0013_alter_recipe_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('bank', 'Chuyển khoản ngân hàng'), ('momo', 'Momo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('vegetarian', 'Món chay'), ('meat', 'Món mặn'), ('dessert', 'Món tráng miệng')], default='meat', max_length=50),
        ),
    ]
