# Generated by Django 5.1.1 on 2025-07-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dopamine', '0016_category_parent_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_sub',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
    ]
